### ISSUE TITLE
crash with --num-threads set

### ISSUE THREAD

**Issue by garfieldnate** [tatuylonen/wiktextract#151]
This may be another OSX thing, but I've found that I cannot use the `--num-threads` option, as it always leads to a crash.

Example run command:

    ./wiktwords --all --language Vietnamese --pages-dir pages --num-threads 2 --cache /tmp/wikt-cache --out vn_out.jsonl enwiktionary-latest-pages-articles.xml.bz2 | tee log_vn_1.txt

And here's the error output:

    multiprocessing.pool.RemoteTraceback:
    """
    Traceback (most recent call last):
    File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
        result = (True, func(*args, **kwds))
    File "/Users/nate/dev/workspaces/python_workspace/wiktextract/env/lib/python3.9/site-packages/wikitextprocessor/core.py", line 60, in phase2_page_handler
        ctx.start_page(title)
    AttributeError: 'NoneType' object has no attribute 'start_page'
    """

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
    File "/Users/nate/dev/workspaces/python_workspace/wiktextract/./wiktwords", line 277, in <module>
        parse_wiktionary(ctx, args.path, config, word_cb, capture_cb,
    File "/Users/nate/dev/workspaces/python_workspace/wiktextract/wiktextract/wiktionary.py", line 134, in parse_wiktionary
        return reprocess_wiktionary(ctx, config, word_cb, capture_cb)
    File "/Users/nate/dev/workspaces/python_workspace/wiktextract/wiktextract/wiktionary.py", line 148, in reprocess_wiktionary
        thesaurus_data = extract_thesaurus_data(ctx, config)
    File "/Users/nate/dev/workspaces/python_workspace/wiktextract/wiktextract/thesaurus.py", line 254, in extract_thesaurus_data
        for word, linkages in ctx.reprocess(page_handler, autoload=False):
    File "/Users/nate/dev/workspaces/python_workspace/wiktextract/env/lib/python3.9/site-packages/wikitextprocessor/core.py", line 1389, in reprocess
        for success, title, t, ret in \
    File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 870, in next
        raise value
    AttributeError: 'NoneType' object has no attribute 'start_page'

**Comment by xxyzz** [comment]
`--num-threads` is for Linux according to the project README.

I guess the reason is Python uses `spawn` to start new process on mac and windows, so the child process doesn't inherit  the `ctx` object: https://github.com/tatuylonen/wikitextprocessor/blob/a63165f3f1a65c5be18df3d14b578db6a242f894/wikitextprocessor/core.py#L128-L137

**Comment by garfieldnate** [comment]
Ah, if that was the intended behavior then I think on other OS's the `--num-threads` argument should be discarded and a warning printed.

Thanks for pointing out the reason behind the issue; I think there's a way to fix this. I'll look into it.

**Comment by garfieldnate** [comment]
Hmm, doesn't seem to be supported in core Python on OSX. You'd have to use gevent or something of that sort. I do think preventing the crash by ignoring the flag would still be good, though.

**Comment by kristian-clausal** [comment]
I've merged your pull request, it seemed like a reasonable workaround.
