### ISSUE TITLE
wiktwords not working

### ISSUE THREAD

**Issue by manugoswami** [tatuylonen/wiktextract#371]
Hi ,

After successfully building wiktwords from sources, still not able to extract and convert wiktionary data to jason and .db
using command

wiktwords --all --all-languages --out data.json enwiktionary-latest-pages-articles.xml.bz2

error 
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

Capturing words for all available languages
2023-10-19 21:17:00,307 INFO: First phase - extracting templates, macros, and pages
2023-10-19 21:17:00,308 INFO: skip_extract_dump: False, save_pages_path: None
2023-10-19 21:17:00,309 INFO: dump file path: enwiktionary-latest-pages-articles.xml.bz2
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\ons_4\ons_wiktextprocessor\.venv\Scripts\wiktwords.exe\__main__.py", line 7, in <module>
  File "D:\ons_4\ons_wiktextprocessor\.venv\Lib\site-packages\wiktextract\wiktwords.py", line 450, in main
    parse_wiktionary(
  File "D:\ons_4\ons_wiktextprocessor\.venv\Lib\site-packages\wiktextract\wiktionary.py", line 115, in parse_wiktionary
    process_dump(
  File "D:\ons_4\ons_wiktextprocessor\.venv\Lib\site-packages\wikitextprocessor\dumpparser.py", line 112, in process_dump
    parse_dump_xml(ctx, path, namespace_ids)
  File "D:\ons_4\ons_wiktextprocessor\.venv\Lib\site-packages\wikitextprocessor\dumpparser.py", line 39, in parse_dump_xml
    with decompress_dump_file(dump_path) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ons_4\ons_wiktextprocessor\.venv\Lib\site-packages\wikitextprocessor\dumpparser.py", line 25, in decompress_dump_file
    p = subprocess.Popen(
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\manug\anaconda3\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\manug\anaconda3\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

Kindly regards,
Manu

**Comment by xxyzz** [comment]
The "dumpparser.py" file in the wikitextprocessor package requires "lbzcat" or "bzcat" to extract the ".bz2" file, you must have one of them installed.

**Comment by manugoswami** [comment]
Hi,

Thanks for the reply. I cannot find lbzcat or bzcat anywhere in windows 10 or in google search. Kindly inform how to get these packages or libraries?

Kind regards,
Manu

**Comment by manugoswami** [comment]
Hi,

Many Many thanks for your responses. I simply built bizip2 and renamed the .exe file to bzcat !!!!!

Kindly regards,
Manu

**Comment by Vuizur** [comment]
I could also get it to stop throwing this error using the prebuilt .exe (and dll) from https://github.com/philr/bzip2-windows and renaming it to bzcat.exe + putting it in the wiktextract location.
