### ISSUE TITLE
python 3 UnicodeEncodeError: 'ascii' codec can't encode character '\xed' 

### ISSUE THREAD

**Issue by krasi0** [tatuylonen/wiktextract#9]
This is the error I get when using the following command (under python3) :
$ wiktwords data/enwiktionary-latest-pages-articles.xml.bz2 --out wikt.words --language English --linkages --compounds --redirects --statistics 
-------------------------------------------
Valparaiso INSIDE GLOSS: 'alt sp' Traceback (most recent call last):
  File "/usr/local/bin/wiktwords", line 4, in <module>
    __import__('pkg_resources').run_script('wiktextract==0.2.0', 'wiktwords')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/wiktextract-0.2.0-py3.6.egg/EGG-INFO/scripts/wiktwords", line 169, in <module>
  File "/usr/local/lib/python3.6/dist-packages/wiktextract-0.2.0-py3.6.egg/wiktextract/wiktionary.py", line 2539, in parse_wiktionary
  File "src/lxml/etree.pyx", line 3467, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1860, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1880, in lxml.etree._parseFilelikeDocument
  File "src/lxml/parser.pxi", line 1775, in lxml.etree._parseDocFromFilelike
  File "src/lxml/parser.pxi", line 1187, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src/lxml/parsertarget.pxi", line 192, in lxml.etree._TargetParserContext._handleParseResultDoc
  File "src/lxml/parsertarget.pxi", line 180, in lxml.etree._TargetParserContext._handleParseResultDoc
  File "src/lxml/etree.pyx", line 318, in lxml.etree._ExceptionContext._raise_if_stored
  File "src/lxml/saxparser.pxi", line 485, in lxml.etree._handleSaxEnd
  File "src/lxml/parsertarget.pxi", line 99, in lxml.etree._PythonSaxParserTarget._handleSaxEnd
  File "/usr/local/lib/python3.6/dist-packages/wiktextract-0.2.0-py3.6.egg/wiktextract/wiktionary.py", line 2484, in end
  File "/usr/local/lib/python3.6/dist-packages/wiktextract-0.2.0-py3.6.egg/wiktextract/wiktionary.py", line 2333, in parse_text
  File "/usr/local/lib/python3.6/dist-packages/wiktextract-0.2.0-py3.6.egg/wiktextract/wiktionary.py", line 2333, in <genexpr>
  File "/usr/local/lib/python3.6/dist-packages/wiktextract-0.2.0-py3.6.egg/wiktextract/wiktionary.py", line 2269, in iter_fn
  File "/usr/local/lib/python3.6/dist-packages/wiktextract-0.2.0-py3.6.egg/wiktextract/wiktionary.py", line 1663, in parse_preamble
  File "/usr/local/lib/python3.6/dist-packages/wiktextract-0.2.0-py3.6.egg/wiktextract/wiktionary.py", line 1607, in parse_sense
UnicodeEncodeError: 'ascii' codec can't encode character '\xed' in position 16: ordinal not in range(128)

**Comment by krasi0** [comment]
setting `PYTHONIOENCODING=utf-8`
seems to do the trick
